proto now uses the Rakudo that came with Parrot 0.9.0

diff --git a/proto b/proto
--- a/proto
+++ b/proto
@@ -20,13 +20,15 @@ else
     exit 1;
 fi
 
-if command -v git >/dev/null 2>&1; then
-    echo -n
-else
-    echo "Cannot find 'git'. You need to install that first."
-    echo "Go to http://git-scm.com/download and follow the instructions there."
-    exit 1;
-fi
+# NB: No need to check for git until bleeding-edge Rakudo is used. See below.
+
+# if command -v git >/dev/null 2>&1; then
+#     echo -n
+# else
+#     echo "Cannot find 'git'. You need to install that first."
+#     echo "Go to http://git-scm.com/download and follow the instructions there."
+#     exit 1;
+# fi
 
 # 2. Check $PARROT_DIR
 # 3. Check that it's a Parrot dir
@@ -83,34 +85,59 @@ if [[ !(-e $PARROT_DIR/parrot) ]]; then
         exit 1;
     fi
     rm -f make.log
+    cd -
 fi
 
-# 5. Check whether the languages/rakudo dir exists
-if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
-    echo -n "Downloading Perl 6... "
-    cd $PARROT_DIR/languages
-    git clone git://github.com/rakudo/rakudo.git >> download.log 2>&1
-    echo ''
-    if (($? != 0)); then
-        echo "The download failed. See download.log for details."
-        exit 1;
-    fi
-    if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
-        echo "Download failed. See download.log for details."
-        exit 1;
-    fi
-    rm -f download.log
-fi
+# NB: Commenting out the following two steps temporarily: when we use the
+#     0.9.0 release of Parrot, we cannot use git Rakudo, because of recent
+#     API changes. Later, I'll add an option to use bleeding-edge Parrot
+#     and Rakudo.
 
-# 6. Check whether it contains a 'perl6.pbc' file
-if [[ !(-e $PARROT_DIR/languages/rakudo/perl6.pbc) ]]; then
+# # 5. Check whether the languages/rakudo dir exists
+# if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
+#     echo -n "Downloading Perl 6... "
+#     cd $PARROT_DIR/languages
+#     git clone git://github.com/rakudo/rakudo.git >> download.log 2>&1
+#     echo ''
+#     if (($? != 0)); then
+#         echo "The download failed. See download.log for details."
+#         exit 1;
+#     fi
+#     if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
+#         echo "Download failed. See download.log for details."
+#         exit 1;
+#     fi
+#     rm -f download.log
+#     cd -
+# fi
+# 
+# # 6. Check whether it contains a 'perl6.pbc' file
+# if [[ !(-e $PARROT_DIR/languages/rakudo/perl6.pbc) ]]; then
+#     echo -n "Building Perl 6... "
+#     cd $PARROT_DIR/languages/rakudo
+#     echo -n > make.log
+#     if [[ -e Makefile ]]; then
+#         make realclean >> make.log 2>&1
+#     fi
+#     perl Configure.pl  >> make.log 2>&1
+#     make               >> make.log 2>&1
+#     echo ''
+#     if (($? != 0)); then
+#         echo "Build failed. See make.log for details."
+#         exit 1;
+#     fi
+#     if [[ !(-e perl6.pbc) ]]; then
+#         echo "Build failed. See make.log for details."
+#         exit 1;
+#     fi
+#     rm -f make.log
+#     cd -
+# fi
+
+if [[ !(-e $PARROT_DIR/languages/perl6/perl6.pbc) ]]; then
     echo -n "Building Perl 6... "
-    cd $PARROT_DIR/languages/rakudo
+    cd $PARROT_DIR/languages/perl6
     echo -n > make.log
-    if [[ -e Makefile ]]; then
-        make realclean >> make.log 2>&1
-    fi
-    perl Configure.pl  >> make.log 2>&1
     make               >> make.log 2>&1
     echo ''
     if (($? != 0)); then
@@ -122,6 +149,7 @@ if [[ !(-e $PARROT_DIR/languages/rakudo/perl6.pbc) ]]; then
         exit 1;
     fi
     rm -f make.log
+    cd -
 fi
 
 echo "Parrot and Perl 6 are present and built."
