removed svn dep, download parrot and rakudo, small changes

diff --git a/proto b/proto
--- a/proto
+++ b/proto
@@ -3,19 +3,20 @@
 # This bootstrapping script assumes as little as possible about the user's
 # setup. It tries to establish, one after another, the following things:
 #
-# 1. That Perl, svn and git are installed
+# 1. That perl and git are installed
 # 2. That $PARROT_DIR is set.
 # 3. That $PARROT_DIR points to a directory containing Parrot.
 # 4. That it contains a 'parrot' executable.
 # 5. That the $PARROT_DIR/languages/rakudo directory exists.
 # 6. That it contains a 'perl6.pbc' file.
 
-# 1. Check Perl, git and svn
+# 1. Check perl and git
 if (which -s perl); then
     echo -n
 else
     echo "Cannot find 'perl'. You need to install that first."
-    echo "Go to http://www.perl.org and follow the instructions there."
+    echo "Go to http://www.perl.org/get.html and follow the instructions there."
+    # TODO: Maybe autodetect various packaging systems that can download perl
     exit 1;
 fi
 
@@ -23,48 +24,62 @@ if (which -s git); then
     echo -n
 else
     echo "Cannot find 'git'. You need to install that first."
-    # TODO: Find git homepage
-    exit 1;
-fi
-
-if (which -s svn); then
-    echo -n
-else
-    echo "Cannot find 'svn'. You need to install that first."
-    # TODO: Find svn homepage
+    echo "Go to http://git-scm.com/download and follow the instructions there."
     exit 1;
 fi
 
 # 2. Check $PARROT_DIR
-if [[ -z $PARROT_DIR ]]; then
-    echo "You don't have \$PARROT_DIR set."
-    # TODO: Have a short chat with the user and maybe download Parrot
-    exit 1;
-fi
-
 # 3. Check that it's a Parrot dir
-if [[ !(-e $PARROT_DIR/README) ||
+if [[ -z $PARROT_DIR ||
+      !(-e $PARROT_DIR/README) ||
       $(head -n1 $PARROT_DIR/README) != 'This is Parrot'* ]]; then
-    echo "Your \$PARROT_DIR variable doesn't seem to point to a Parrot installation."
-    # TODO: Either just die here, or same as 1.
-    exit 1;
+    echo -n "Downloading Parrot... ";
+    # TODO: Figure out a way to find the latest release of Parrot, instead
+    #       of hardcoding it here.
+    VERSION='0.9.0'
+    FTP_PATH="ftp.parrot.org/pub/parrot/releases/devel/$VERSION"
+    TARFILE="parrot-$VERSION.tar.gz"
+    wget ftp://$FTP_PATH/$TARFILE > download.log 2>&1
+    if (($? != 0)); then
+        echo ''
+        echo "The download failed. See download.log for details."
+        exit 1;
+    fi
+    tar xzvf $TARFILE            >> download.log 2>&1
+    echo ''
+    if (($? != 0)); then
+        echo "The download failed. See download.log for details."
+        exit 1;
+    fi
+    DIRNAME=`basename $TARFILE .tar.gz`
+    if [[ !(-d $DIRNAME) ]]; then
+        echo "Download succeeded strangely. Giving up. See download.log for details."
+        exit 1;
+    fi
+    export PARROT_DIR=`pwd`/$DIRNAME
+    # TODO: Refine evil modification-without asking of .bash_profile
+    cat >> ~/.bash_profile <<EOF
+export PARROT_DIR=`pwd`/$DIRNAME
+EOF
+    rm -f $TARFILE download.log
 fi
 
 # 4. Check whether it contains a Parrot executable
 if [[ !(-e $PARROT_DIR/parrot) ]]; then
-    echo "Building Parrot..."
+    echo -n "Building Parrot... "
     cd $PARROT_DIR
     if [[ -e Makefile ]]; then
         make realclean > make.log 2>&1 
     fi
     perl Makefile.PL  >> make.log 2>&1
     make              >> make.log 2>&1
+    echo ''
     if (($? != 0)); then
-        echo "The build process failed. See make_result for details."
+        echo "The build process failed. See make.log for details."
         exit 1;
     fi
     if [[ !(-e parrot) ]]; then
-        echo "Build succeeded strangely. Giving up. See make_result for details."
+        echo "Build succeeded strangely. Giving up. See make.log for details."
         exit 1;
     fi
     rm -f make.log
@@ -72,26 +87,38 @@ fi
 
 # 5. Check whether the languages/rakudo dir exists
 if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
-    echo "Downloading Perl 6..."
-    # TODO: Download Rakudo from github
-    exit 0;
+    echo -n "Downloading Perl 6... "
+    cd $PARROT_DIR/languages
+    git clone git://github.com/rakudo/rakudo.git >> download.log 2>&1
+    echo ''
+    if (($? != 0)); then
+        echo "The download failed. See download.log for details."
+        exit 1;
+    fi
+    if [[ !(-d $PARROT_DIR/languages/rakudo) ]]; then
+        echo "Download succeeded strangely. Giving up. See download.log for details."
+        exit 1;
+    fi
+    rm -f download.log
 fi
 
 # 6. Check whether it contains a 'perl6.pbc' file
 if [[ !(-e $PARROT_DIR/languages/rakudo/perl6.pbc) ]]; then
-    echo "Building Perl 6..."
+    echo -n "Building Perl 6... "
     cd $PARROT_DIR/languages/rakudo
     if [[ -e Makefile ]]; then
         make realclean > make.log 2>&1
     fi
     perl Configure.pl >> make.log 2>&1
     make              >> make.log 2>&1
+    echo ''
     if (($? != 0)); then
-        echo "The build process failed. See make_result for details."
+        echo "The build process failed. See make.log for details."
         exit 1;
     fi
     if [[ !(-e perl6.pbc) ]]; then
-        echo "Build succeeded strangely. Giving up. See make_result for details."
+        echo "Build succeeded strangely. Giving up. See make.log for details."
+        exit 1;
     fi
     rm -f make.log
 fi
